name: Build and deploy Plagiarism detector

on: 
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master


jobs:
  Checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

